[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"
    scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.leresolver.acme]
  email = "ashur.rafiev@ncl.ac.uk"
  storage = "acme.json"
  [certificatesResolvers.leresolver.acme.tlsChallenge]

[providers.docker]
  network = "traefik"
  exposedByDefault = false
